Demo - Running an EnergyPlus Simulation
=======================================

To run an EnergyPlus simulation we need:

* the directory on the local machine where EnergyPlus is installed.
* the filepath of an EnergyPlus input file (either an .idf or an .epJSON file).
* the filepath of an EnergyPlus weather file (an .epw file).
* the directory on the local machine where the simulation results will be stored.

Using these four pieces of information, the `runsim` function can now run an EnergyPlus simulation. 

.. code-block:: python
   :lineno-start: 1

   >>> from eprun import runsim
   >>> result=runsim(ep_dir=r'C:\EnergyPlusV9-4-0',
   >>>               input_filepath='1ZoneUncontrolled.idf',
   >>>               epw_filepath='USA_CO_Golden-NREL.724666_TMY3.epw',
   >>>               sim_dir='simulation_results')
   >>> print(type(result))
   <class 'eprun.epresult.EPResult'>
   
The `runsim` function calls the *energyplus.exe* application in the EnergyPlus install directory using 
the `subprocess.run` method from the `Python Standard Library <https://docs.python.org/3/library/index.html>`_.

The `runsim` function returns a `EPResult` object instance. 
This object contains links to the EnergyPlus results files generated by the simulation, as well as the `returncode <subprocess.CompletedProcess.returncode>` 
and `stdout <subprocess.CompletedProcess.stdout>` results of the `subprocess.run` call.

The next section describes the `EPResult` object in more detail.

Further resources
-----------------

* The documentation for the `runsim function <runsim_function>`
* The '`Running an EnergyPlus simulation on the 1ZoneUncontrolled file`_' Jupyter Notebook shows the eprun function in action.
* The EnergyPlus QuickStart guide: https://energyplus.net/quickstart
* The 'Running EnergyPlus: Command Line' section on p15 in the `EnergyPlus Essentials`_ documentation.

.. _Running an EnergyPlus simulation on the 1ZoneUncontrolled file: https://nbviewer.jupyter.org/github/stevenkfirth/eprun/blob/main/examples/Running%20an%20EnergyPlus%20simulation%20on%20the%201ZoneUncontrolled%20file/Running%20an%20EnergyPlus%20simulation%20on%20the%201ZoneUncontrolled%20file.ipynb
.. _EnergyPlus Essentials: https://energyplus.net/quickstart#reading